-- Bantrbox 18+ account gate (phase 1: recording only).
-- The confirmation belongs to the authenticated master account so every
-- managed profile inherits the same age status.

alter table public.master_accounts
  add column if not exists adult_confirmed_at timestamptz,
  add column if not exists adult_policy_version text,
  add column if not exists adult_confirmation_source text;

create table if not exists public.account_consent_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  consent_type text not null,
  policy_version text not null,
  confirmation_source text not null,
  confirmed_at timestamptz not null default now()
);

create index if not exists account_consent_events_user_id_idx
  on public.account_consent_events(user_id, confirmed_at desc);

alter table public.account_consent_events enable row level security;
revoke all on table public.account_consent_events from public, anon, authenticated;

create or replace function public.has_confirmed_adult_status()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.master_accounts
    where user_id = auth.uid()
      and adult_confirmed_at is not null
      and adult_policy_version is not null
  );
$$;

revoke all on function public.has_confirmed_adult_status() from public;
grant execute on function public.has_confirmed_adult_status() to authenticated;

create or replace function public.confirm_adult_status(
  p_policy_version text,
  p_source text default 'unknown'
)
returns timestamptz
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  current_user_id uuid := auth.uid();
  confirmed_time timestamptz := now();
  clean_policy_version text := trim(coalesce(p_policy_version, ''));
  clean_source text := left(trim(coalesce(p_source, 'unknown')), 80);
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;
  if clean_policy_version = '' then
    raise exception 'Age policy version is required';
  end if;

  insert into public.master_accounts (
    user_id,
    signup_source,
    terms_version,
    privacy_version,
    terms_accepted_at,
    privacy_accepted_at,
    adult_confirmed_at,
    adult_policy_version,
    adult_confirmation_source,
    updated_at
  )
  select
    current_user_id,
    coalesce(raw_user_meta_data ->> 'signup_source', 'bantrbox'),
    'bantrbox-terms-2026-08-18plus',
    'bantrbox-privacy-2026-08-18plus',
    confirmed_time,
    confirmed_time,
    confirmed_time,
    clean_policy_version,
    clean_source,
    confirmed_time
  from auth.users
  where id = current_user_id
  on conflict (user_id) do update set
    adult_confirmed_at = coalesce(master_accounts.adult_confirmed_at, excluded.adult_confirmed_at),
    adult_policy_version = excluded.adult_policy_version,
    adult_confirmation_source = excluded.adult_confirmation_source,
    terms_version = excluded.terms_version,
    privacy_version = excluded.privacy_version,
    terms_accepted_at = coalesce(master_accounts.terms_accepted_at, excluded.terms_accepted_at),
    privacy_accepted_at = coalesce(master_accounts.privacy_accepted_at, excluded.privacy_accepted_at),
    updated_at = excluded.updated_at;

  insert into public.account_consent_events (
    user_id,
    consent_type,
    policy_version,
    confirmation_source,
    confirmed_at
  ) values (
    current_user_id,
    'adult_18_plus',
    clean_policy_version,
    clean_source,
    confirmed_time
  );

  return confirmed_time;
end;
$$;

revoke all on function public.confirm_adult_status(text, text) from public;
revoke all on function public.confirm_adult_status(text, text) from anon;
grant execute on function public.confirm_adult_status(text, text) to authenticated;
